# Generated by Django 4.0.1 on 2022-03-17 18:38

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
